services:
  server:
    # image: hsn129/picfixer_image:latest
    build: .
    container_name: picfixer-app
    restart: unless-stopped
    ports:
      - 8000:8000
    # env_file:
    #   - ./server/.env
    environment:
      - LARAVEL_PROJECT_NAME=picfixer
      - LARAVEL_DATABASE_HOST=database
      - LARAVEL_DATABASE_PORT_NUMBER=3306
      - LARAVEL_DATABASE_NAME=picfixer
      - LARAVEL_DATABASE_USER=root
      - LARAVEL_DATABASE_PASSWORD=12345678
      - ALLOW_EMPTY_PASSWORD=no
    depends_on:
      - database

  database:
    image: mysql:8.0
    container_name: picfixer-db
    restart: unless-stopped
    ports:
      - "3306:3306"
    # env_file:
    #   - ./server/.env
    environment:
      - MYSQL_ROOT_PASSWORD=12345678
      - MYSQL_DATABASE=picfixer
      - MYSQL_ROOT_HOST=% # This allows connections from any host
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
