services:
  server:
    # image: hsn129/picfixer_image:latest
    build: .
    container_name: picfixer-app
    restart: unless-stopped
    ports:
      - 8000:80
    env_file:
      - ./server/.env
    depends_on:
      - database

  database:
    image: mysql:8.0
    container_name: picfixer-db
    restart: unless-stopped
    ports:
      - "3306:3306"
    env_file:
      - ./server/.env
    # environment:
    #   - MYSQL_ROOT_PASSWORD=placeholder_password
    #   - MYSQL_DATABASE=placeholder_database_name
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
