services:
  server:
    # image: hsn129/picfixer_image:latest
    build: .
    container_name: picfixer-app
    restart: unless-stopped
    ports:
      - 8000:80
    env_file:
      - ./server/.env
    depends_on:
      - database

  database:
    image: mysql:8.0
    container_name: picfixer-db
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=12345678
      - MYSQL_DATABASE=picfixer_electronjs_db
      - MYSQL_ROOT_HOST=% # This allows connections from any host
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
