name: Deploy Laravel Backend to EC2

on:
  push:
    branches:
      - main

jobs:
  build-and-push-image:
    name: Build, Test, and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          extensions: mbstring, pdo, mysql
          coverage: none

      - name: Install Laravel Dependencies
        working-directory: ./server
        run: composer install --prefer-dist

      - name: Copy .env example
        working-directory: ./server
        run: cp .env.example .env

      - name: Generate Application Key
        working-directory: ./server
        run: php artisan key:generate

      - name: Run Laravel Tests
        working-directory: ./server
        run: php artisan test

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/picfixer_image:latest .

      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/picfixer_image:latest

  deploy-to-ec2:
    name: Deploy to EC2
    needs: build-and-push-image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd /home/ubuntu/picfixer
            sudo docker-compose down
            sudo docker rmi ${{ secrets.DOCKER_USERNAME }}/picfixer_image:latest || true
            sudo docker-compose up -d
            sudo docker exec picfixer-app php artisan migrate --force
